### PR TITLE
Fix embed issues

### LINKED ISSUE #119: Fullbleed article not able to render youtube embed link
For example on https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/gerry-mcilroy-bet-rory-mcilroy-british-open-2023 the youtube embed isn't loading because it was not imported cc @hsaginor

### LINKED ISSUE #141: Embed should support autoplay functionality
For example for the columns block on https://main--helix-sportsmagazine--headwirecom.hlx.page/ or the embed block in the article here https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/1/tom-kim-dunks-approach-shot-asks-fantastic-question-sentry-toc

### PR DESCRIPTION
**Pull request by Lauraa1003**
Fix #141 
Fix #119 

Test URLs (#119)
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/british-open-2023-the-most-emotional-moment-of-tiger-woods-career
- After: https://fix-issues--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/british-open-2023-the-most-emotional-moment-of-tiger-woods-career

Test URLs (#141)
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/
- After: https://fix-issues--helix-sportsmagazine--headwirecom.hlx.page/

### CODE REVIEW

File: blocks/embed/embed.js [hunk 1]
```diff
@@ -33,32 +33,62 @@ const embedInstagram = (url) => {
...
+  if (autoplay) {
+    params.set('muted', '1');
+    params.set('autoplay', '1');
+  }
   if (url.origin.includes('youtu.be')) {
-    [, vid] = url.pathname.split('/');
+    const [, vid] = url.pathname.split('/');
+    youtubeUrl = new URL(`https://www.youtube.com/embed/${vid}`);
+    params = youtubeUrl.searchParams;
+    params.set('rel', '0'); // Set rel=0 to prevent showing related videos
```
Comment (icaraps) [inline blocks/embed/embed.js:46]: nice 👍

File: blocks/embed/embed.js [hunk 2]
```diff
@@ -112,14 +146,14 @@ export default function decorate(block) {
     wrapper.innerHTML = '<div class="embed-placeholder-play"><button title="Play"></button></div>';
     wrapper.prepend(placeholder);
     wrapper.addEventListener('click', () => {
-      loadEmbed(block, link, true);
+      loadEmbed(block, link, false);
```
Comment (icaraps) [inline blocks/embed/embed.js:149]: @Lauraa1003 We can define autoplay as toggleable by the author eg

```
embed (autoplay)
--- 
link
```

So you can check for the className `autoplay`: 

`const autoplay = block.classList.contains('autoplay')`

**Review by icaraps — CHANGES_REQUESTED** [review]
