### PR TITLE
Query initialization fixes

### LINKED ISSUE #248: Hero interferes with Card hero variation
On https://main--helix-sportsmagazine--headwirecom.hlx.page/drafts/ringel/test, I have an example of page with a hero and card hero variation. It looks like the store query handler calls the hero function which seems wrong...

Screenshot 2023-09-18 at 10 24 52

### LINKED ISSUE #249: Same sheet queries with different category won't load
If I have 2 queries on the page with the same name but from different category (eg article and gallery), it doesn't even try loading the second query see on https://main--helix-sportsmagazine--headwirecom.hlx.page/drafts/ringel/test2

### PR DESCRIPTION
**Pull request by DriftingSands**
Adjusted query initialization queryselectos, so block variations that share a name with a block-type, won't get the wrong limits.

Adjusted generated querymap to name object keys using both spreadsheet name and sheet names so blocks with matching sheet names but differing spreadsheets will no longer break eachothers queries.

Fix #248 
Fix #249 

Test URLs:
- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page
- After: https://query-initialization-fix--helix-sportsmagazine--headwirecom.hlx.page

- Before: https://main--helix-sportsmagazine--headwirecom.hlx.page/drafts/ringel/test2
- After: https://query-initialization-fix--helix-sportsmagazine--headwirecom.hlx.page/drafts/ringel/test2

### CODE REVIEW

File: scripts/scripts.js [hunk 1]
```diff
@@ -557,7 +557,7 @@ window.store = new (class {
     this._blockQueryLimit = {
       hero: (block) => {
         const firstHero = document.querySelector('.hero.block[data-block-name="hero"]');
-        if (firstHero.isEqualNode(block)) {
+        if (firstHero?.isEqualNode(block)) {
```
Comment (icaraps) [inline scripts/scripts.js:560]: This shouldn't be necessary right ? In the sense that hero will only be called if there's a hero on the page so `firstHero` can never be null ?

Comment (DriftingSands) [reply scripts/scripts.js:560]: yeah thats true, now that the queryselector is updated. I can change it back
